name: Build Documentation

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-ci-workflow
  cancel-in-progress: true

permissions:
  contents: read  # Required to read repository contents
  id-token: write  # Required to request an ID token for deployment    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r Docs/requirements.txt

      - name: Build documentation
        run: |
          cd Docs
          make clean
          make html

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          git add Docs/build/html
          git commit -m "Deploy documentation"
          git push origin gh-pages --force          
