name: Build Documentation

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-ci-workflow
  cancel-in-progress: true

permissions:
  contents: read  # Required to read repository contents
  id-token: write  # Required to request an ID token for deployment    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r Docs/requirements.txt

      - name: Build documentation
        run: |
          cd Docs
          make clean
          make html

      - name: Upload documentation as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: Docs/build/html/  # Ensure this path is correct          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          folder: Docs/build/html/
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
